[general]
name = "relu-tvm-ffi"

backends = [
    "cuda",
]

[tvm-ffi]
src = [
    "tvm-ffi-ext/tvm_ffi_binding.cpp",
]

[kernel.relu]
backend = "cuda"
depends = ["torch"]
src = ["relu_cuda/relu.cu"]
