name: "Check build variants"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened] # trigger on PRs
  workflow_dispatch:

jobs:
  build:
    name: Check build variants
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Generate variants JSON
        run: nix eval --raw .#lib.allBuildVariantsJSON | nix run nixpkgs#jq 'walk(if type == "array" then sort else . end)' > builder/build-variants.json
      - name: Check if variants JSON is up-to-date
        run: |
          if git diff --exit-code builder/build-variants.json; then
            echo "âœ… variants.json is up-to-date"
          else
            echo "ðŸ›‘ regenerate variants.json: nix eval --raw .#lib.allBuildVariantsJSON | nix run nixpkgs#jq 'walk(if type == "array" then sort else . end)' > builder/build-variants.json"
            exit 1
          fi
      - name: Generate variants Markdown
        run: nix run nixpkgs#python3 builder/scripts/gen_variants_markdown.py
      - name: Check if variants Markdown is up-to-date
        run: |
          if git diff --exit-code docs/source/builder/build-variants.md; then
            echo "âœ… docs/source/buidler/build-variants.md is up-to-date"
          else
            echo "ðŸ›‘ regenerate docs/build-variants: nix run nixpkgs#python3 builder/scripts/gen_variants_markdown.py"
            exit 1
          fi
